In [1]:
%pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.


In [2]:
pip install -q -U numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [4]:
array1D=np.array([1,2,3])
print(array1D)
print(type(array1D))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
array2D=np.array([[1,2,3],[4,5,6]])
print(array2D)
print(type(array2D))


[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
