In [ ]:
pip install -q -U numpy

In [11]:
import numpy as np
arr1=np.array([1,2,3])
print("1D array: ",arr1)

arr2=np.arange(1,10).reshape(3,3)
print("2D array: ",arr2)

arr3=np.arange(1,28).reshape(3,3,3)
print("3D array: ",arr3)

print(arr3[1,1,1])

1D array:  [1 2 3]
2D array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
3D array:  [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
14


In [20]:
arr1=np.array([[1,2,3],[4,5,6]],dtype=np.int64)
print(arr1)

arr=np.ones((3,3),dtype=np.int32)
print(arr)
arr2=np.identity(2,dtype=np.int32)
print(arr2)

#Linspace
arr1=np.linspace(-10,10,5)
print(arr1)
print(arr1.astype("int32"))

[[1 2 3]
 [4 5 6]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[1 0]
 [0 1]]
[-10.  -5.   0.   5.  10.]
[-10  -5   0   5  10]


In [23]:
arr1=np.array([[1,2,3],[4,5,6]],dtype=np.int64)
print(np.max(arr1,axis=0))
print(np.max(arr1,axis=1))
#np.min()
#np.sum
#np.prod
#np.diff

[4 5 6]
[3 6]


In [24]:
#statistical function
#np.mean() np.std() np.var() np.median()

#trigonometrix
#np.sin() np.cos() np.cosec() np.sec() np.tan() np.cot()

#dot product
#np.dot()

#log
#np.log()

#exponential
#np.exp()


In [28]:
#round ceil floor

arr=np.array([[1.2,3.9,4.5],[4.6,6.5,7.9]])
print(arr.round().astype("int32"))

print(np.ceil(arr).astype("int32"))

print(np.floor(arr).astype("int32"))

[[1 4 4]
 [5 6 8]]
[[2 4 5]
 [5 7 8]]
[[1 3 4]
 [4 6 7]]


In [32]:
# nD -> 1D

arr=np.arange(1,17).reshape(4,4)
print(arr)
arr=np.ravel(arr)
print(arr)
print(arr.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
16
